apiVersion: v1
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: java-crud-db
      app.kubernetes.io/component: java-crud-db
      app.kubernetes.io/instance: java-crud-db
    name: java-crud-db
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: java-crud-db
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          deployment: java-crud-db
      spec:
        containers:
        - env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          image: image-registry.openshift-image-registry.svc:5000/d0278b-tools/postgres:latest
          imagePullPolicy: IfNotPresent
          name: java-crud-db
          ports:
          - containerPort: 5432
            protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: 100Mi
            limits:
              cpu: "500m"
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: java-crud-db-volume-1
          - mountPath: /docker-entrypoint-initdb.d
            name: java-crud-db-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: java-crud-db-volume-1
          persistentVolumeClaim:
            claimName: java-crud-db-vol
        - configMap:
            defaultMode: 420
            name: postgres-init
          name: java-crud-db-volume
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"java-crud"}]'
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: java-crud-db
    name: java-crud-db
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      deployment: java-crud-db
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: java-crud-db
    name: java-crud-db-vol
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 250Mi
    storageClassName: netapp-file-standard
    volumeMode: Filesystem
- apiVersion: v1
  data:
    initdb.sql: "CREATE DATABASE testdb;\n \\c testdb;\nCREATE TABLE tutorials\n(id BIGSERIAL PRIMARY KEY NOT NULL\n,title VARCHAR(255)\n,description VARCHAR(255)\n,published BOOLEAN\n);"
  kind: ConfigMap
  metadata:
    labels:
      app: java-crud-db
    name: postgres-init
kind: Template
metadata:
  selfLink: ""
parameters:
- name: TAG
  description: "imagestream tags to subscribe to"
  value: dev
  required: true
