kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/bolyachevets/spring-boot-jdbctemplate-postgresql.git'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '4304734593'
  name: spring-boot-jdbctemplate-postgresql-git
  generation: 2
  namespace: d0278b-test
  labels:
    app: spring-boot-jdbctemplate-postgresql-git
    app.kubernetes.io/component: spring-boot-jdbctemplate-postgresql-git
    app.kubernetes.io/instance: spring-boot-jdbctemplate-postgresql-git
    app.kubernetes.io/name: spring-boot-jdbctemplate-postgresql-git
    app.kubernetes.io/part-of: spring-boot-jdbctemplate-postgresql-git-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'spring-boot-jdbctemplate-postgresql-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-el7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bolyachevets/spring-boot-jdbctemplate-postgresql.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: spring-boot-jdbctemplate-postgresql-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: spring-boot-jdbctemplate-postgresql-git-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
