kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: postgres
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'postgres:latest'
  resources: {}
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 1
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |
      FROM postgis/postgis:13-3.1
      ENV POSTGRES_DB=geomark
      ENV POSTGRES_USER=postgres
      ENV PGDATA /var/lib/postgresql/data/pgdata
      ENV POSTGRES_PASSWORD=postgres
  triggers:
    - type: ConfigChange
  runPolicy: Serial
